# Learning Numpy and pandas for Data analysis
deal only numeric values
Super fast Processing
Structure = Numpy array 

In [ ]:
Numpy-numerical python

# Creating a numpy Array
1- diemnsional Array

In [3]:
import numpy as np

In [15]:
# using python list
lst=[1,2,3,4,5,6,7,8,9,10]
arr1d = np.array(lst)
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
# using python list
lst=[1,2,3,4,5,6,7,8,9,10]
print(type(lst))
arr1d = np.array(lst)
type(arr1d)

<class 'list'>


numpy.ndarray

In [9]:
len(arr1d)

10

In [10]:
lst[2]

3

In [14]:
lst[-1] =10

In [15]:
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [17]:
lst*2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [19]:
for a in lst:
    print (a*2)

2
4
6
8
10
12
14
16
18
20


In [21]:
double= []
for a in lst:
    print (a*2)
    double.append(a*2)
    double

2
4
6
8
10
12
14
16
18
20


# vectorized operation

In [22]:
arr1d*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [23]:
arr1d*10

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [24]:
arr1d.size

10

In [26]:
arr1d.ndim

1

In [31]:
arr1d.shape

(10,)

In [32]:
arr1d.shape
type(arr1d.shape)

tuple

In [36]:
# using numpy arange
arr1d=np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 2D array 

In [40]:
# 2d array from python list
lst2d=[[1,2,3],[3,4,5],[6,7,8]]
lst2d

[[1, 2, 3], [3, 4, 5], [6, 7, 8]]

In [41]:
arr2d = np.array(lst2d)
arr2d

array([[1, 2, 3],
       [3, 4, 5],
       [6, 7, 8]])

In [42]:
arr2d.shape

(3, 3)

In [43]:
arr2d.ndim

2

In [45]:
arr2d = np.arange(36).reshape(12,3)
arr2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29],
       [30, 31, 32],
       [33, 34, 35]])

In [131]:
arr2d = np.arange(36).reshape(6,6)
arr2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [47]:
arr2d.shape

(6, 6)

In [48]:
arr2d.ndim

2

In [5]:
list_prac = [[1,2,3],[4,5,7,8],[6,7,8]]

In [6]:
arr4d = np.array(list_prac)
arr4d

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [17]:
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
arr1d[7]


8

In [20]:
arr1d[4:8]

array([5, 6, 7, 8])

In [21]:
arr1d[-1]

10

In [23]:
arr1d[4:2]

array([], dtype=int32)

In [25]:
arr2d[2,5]

17

In [29]:
arr2d[2][5]

17

In [78]:
arr2_d = np.arange(36).reshape(4,9)
arr2_d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [35]:
arr2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [39]:
# in slice of 2d array we have two [row, col]
arr2d[1:2,2:6]

array([[ 8,  9, 10, 11]])

In [42]:
arr2d[2:4,2:4]

array([[14, 15],
       [20, 21]])

In [45]:
arr2d[0:6,3:6]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [46]:
arr2d[:6,3:]

array([[ 3,  4,  5],
       [ 9, 10, 11],
       [15, 16, 17],
       [21, 22, 23],
       [27, 28, 29],
       [33, 34, 35]])

In [79]:
arr2_d[2,4:7]

array([22, 23, 24])

In [80]:
arr2_d[:,2]

array([ 2, 11, 20, 29])

In [60]:
arr3d[:,-1].shape

(4,)

In [61]:
arr3d[:,8:].shape

(4, 1)

In [57]:
arr3d.shape

(4, 9)

In [62]:
np.arange(10).reshape(1,10)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [63]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [64]:
np.array(19).ndim

0

In [65]:
np.array([[[19]]]).ndim

3

# fancy indexing


In [81]:
arr2_d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [82]:
arr2_d[:,[5,8,0,3]]

array([[ 5,  8,  0,  3],
       [14, 17,  9, 12],
       [23, 26, 18, 21],
       [32, 35, 27, 30]])

In [73]:
arr2_d[[0,2],[2,7]]

array([ 2, 25])

In [74]:
arr2_d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [84]:
arr2_d[:,::2]

SyntaxError: invalid decimal literal (1999717254.py, line 1)

In [83]:
arr2_d[:,::-2]

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [86]:
#depth, raw, column
arr3d=np.arange(64).reshape(4,4,4)
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [103]:
arr3d[:,2:3,1:3]

array([[[ 9, 10]],

       [[25, 26]],

       [[41, 42]],

       [[57, 58]]])

In [104]:
arr3d[::2,1:3]

array([[[ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[36, 37, 38, 39],
        [40, 41, 42, 43]]])

In [106]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [112]:
np.zeros([4,5], dtype ="int")

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [108]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [110]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [115]:
np.ones([5,5])*10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [116]:
np.ones([5,5])*5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [114]:
np.eye(10,dtype="int")

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [117]:
arr2_d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [118]:
arr2_d.T

array([[ 0,  9, 18, 27],
       [ 1, 10, 19, 28],
       [ 2, 11, 20, 29],
       [ 3, 12, 21, 30],
       [ 4, 13, 22, 31],
       [ 5, 14, 23, 32],
       [ 6, 15, 24, 33],
       [ 7, 16, 25, 34],
       [ 8, 17, 26, 35]])

In [121]:
arr2d2=arr2d
arr2d2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [135]:
arr2d2= np.random.randn(6,6)
arr2d2

array([[-1.49944593,  0.7080864 ,  0.34785222, -0.75606702, -1.13533565,
        -1.59728843],
       [ 0.48738061,  1.12736419,  0.77942011, -0.06192057, -1.06340831,
        -0.13854065],
       [ 0.78134737, -0.27489737, -0.12972782,  0.17793169, -0.43158553,
         0.04394502],
       [ 0.06073859,  0.82405903,  1.38728538,  1.24869454, -0.40641124,
         0.27327675],
       [-0.28768588,  0.11419624,  0.57548047,  0.15196768, -1.23389953,
         0.7730104 ],
       [ 1.62634561,  0.04170678,  0.25644517,  1.20637725,  0.69595935,
        -0.10899025]])

In [133]:
arr2d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [136]:
arr2d2+arr2d

array([[-1.49944593,  1.7080864 ,  2.34785222,  2.24393298,  2.86466435,
         3.40271157],
       [ 6.48738061,  8.12736419,  8.77942011,  8.93807943,  8.93659169,
        10.86145935],
       [12.78134737, 12.72510263, 13.87027218, 15.17793169, 15.56841447,
        17.04394502],
       [18.06073859, 19.82405903, 21.38728538, 22.24869454, 21.59358876,
        23.27327675],
       [23.71231412, 25.11419624, 26.57548047, 27.15196768, 26.76610047,
        29.7730104 ],
       [31.62634561, 31.04170678, 32.25644517, 34.20637725, 34.69595935,
        34.89100975]])

In [140]:
a =np.arange(6).reshape(3,2)
b =np.arange(6).reshape(2,3)

In [141]:
a+b

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [142]:
b*a

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [143]:
a*b

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [146]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [147]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [144]:
b@a

array([[10, 13],
       [28, 40]])

In [145]:
a@b

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [148]:
a.dot(b)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [149]:
b.dot(a)

array([[10, 13],
       [28, 40]])